---
title: "graphique_en_fonction_des_causes"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
SciViews::R
(biometry <- read_csv("https://docs.google.com/spreadsheets/d/1UfpZvx1_nd7d10vIMAfGVZ1vWyIuzeiKxPL0jfkNSQM/export?format=csv", locale = locale(decimal_mark = ",")))
library(tidyverse)
library(plotly)
library(ggplot2)
library(ggExtra)
data(mpg, package="ggplot2")
library(ggridges)

biometry_IMC <- mutate(biometry, IMC = masse/taille^2)
biometry2 <- mutate(biometry_IMC, surpoid = IMC >= 25 & IMC < 30, obese = IMC> 30, normal = IMC <25 & IMC >= 18.5 , souspoid = IMC < 18.5)

biometry2 <- gather(biometry2,
   souspoid, normal, obese, surpoid, key = "sequences", value = "rapport_imc")

biometry2 <- filter (biometry2, rapport_imc != FALSE)

chart(data = biometry2, ~ factor(0) %fill=% sequences) +
  geom_bar(width = 1) + 
  coord_polar("y", start = 0) +
  theme_void() +
  scale_fill_viridis_d()

```
## mise en place
### Causes déterminantes probables (en théorie) de surpoid ou d'obésité
alcool
fastfood
grignotage
proteine_animale
### facteurs séparant plusieurs domaines
genre
age
### causes qui pourrait déterminer des souspoids ou normaux (ou autres)
acti_profession (facteur)
acti_physique 

#Graphiques
## Alcool
```{r}
biometry_alcoolA <-  filter (biometry2,sequences == "souspoid"  )
biometry_alcoolA <- summarise (biometry_alcoolA, " souspoid" = mean(alcool))

biometry_alcoolB <-  filter (biometry2,sequences == "obese"  )
biometry_alcoolB <- filter (biometry_alcoolB, alcool != "NA")

biometry_alcoolB <- summarise (biometry_alcoolB, " obèses" = mean(alcool))

biometry_alcoolC <-  filter (biometry2,sequences == "surpoid"  )
biometry_alcoolC <- filter (biometry_alcoolC, alcool != "NA")
biometry_alcoolC <- summarise (biometry_alcoolC, "surpoid" = mean(alcool))

biometry_alcoolD <-  filter (biometry2,sequences == "normal"  )
biometry_alcoolD <- filter (biometry_alcoolD, alcool != "NA")

biometry_alcoolD <- summarise (biometry_alcoolD, "normaux" = mean(alcool))

biometry_alcool <- bind_cols( biometry_alcoolA, biometry_alcoolD, biometry_alcoolC, biometry_alcoolB)
knitr::kable(biometry_alcool, digits = 2)

```

## fastfood
```{r}
biometry_fastfoodA <-  filter (biometry2,sequences == "souspoid"  )
biometry_fasfoodA <- filter (biometry_fastfoodA, fastfood != "NA")
biometry_fastfoodA <- summarise (biometry_fastfoodA, "souspoid" = mean(fastfood))

biometry_fastfoodB <-  filter (biometry2, sequences == "obese"  )
biometry_fastfoodB <- filter (biometry_fastfoodB, fastfood != "NA")
biometry_fastfoodB <- summarise (biometry_fastfoodB, "obèses" = mean(fastfood))

biometry_fastfoodC <-  filter (biometry2,sequences == "surpoid"  )
biometry_fastfoodC <- filter (biometry_fastfoodC, fastfood != "NA")
biometry_fastfoodC <- summarise (biometry_fastfoodC, "surpoid" = mean(fastfood))

biometry_fastfoodD <-  filter (biometry2,sequences == "normal"  )
biometry_fastfoodD <- filter (biometry_fastfoodD, fastfood != "NA")
biometry_fastfoodD <- summarise (biometry_fastfoodD, "normales" = mean(fastfood))

biometry_fastfood <- bind_cols( biometry_fastfoodA, biometry_fastfoodD, biometry_fastfoodC, biometry_fastfoodB)

knitr::kable(biometry_fastfood, digits = 2)

```

##grignotage
```{r}
biometry_grignotageA <-  filter (biometry2,sequences == "souspoid"  )
biometry_grignotageA <- filter (biometry_grignotageA, grignotage != "NA")
biometry_grignotageA <- summarise (biometry_grignotageA, " souspoid" = mean(grignotage))

biometry_grignotageB <-  filter (biometry2,sequences == "obese"  )
biometry_grignotageB <- filter (biometry_grignotageB, grignotage != "NA")
biometry_grignotageB <- summarise (biometry_grignotageB, " obèses" = mean(grignotage))

biometry_grignotageC <-  filter (biometry2,sequences == "surpoid"  )
biometry_grignotageC <- filter (biometry_grignotageC, grignotage != "NA")
biometry_grignotageC <- summarise (biometry_grignotageC, " surpoid" = mean(grignotage))

biometry_grignotageD <-  filter (biometry2,sequences == "normal"  )
biometry_grignotageD <- filter (biometry_grignotageD, grignotage != "NA")
biometry_grignotageD <- summarise (biometry_grignotageD, "normales" = mean(grignotage))

biometry_grignotage <- bind_cols( biometry_grignotageA, biometry_grignotageD, biometry_grignotageC, biometry_grignotageB)


knitr::kable(biometry_grignotage, digits = 2)

```

##proteine_animale
```{r}
biometry_PA <-  filter (biometry2,sequences == "souspoid"  )
biometry_PA <- filter (biometry_PA, proteine_animale != "NA")
biometry_PA <- summarise (biometry_PA, "souspoid" = mean(proteine_animale))

biometry_PB <-  filter (biometry2,sequences == "obese"  )
biometry_PB <- filter (biometry_PB, proteine_animale != "NA")
biometry_PB <- summarise (biometry_PB, "obèses" = mean(proteine_animale))

biometry_PC <-  filter (biometry2,sequences == "surpoid"  )
biometry_PC <- filter (biometry_PC, proteine_animale != "NA")
biometry_PC <- summarise (biometry_PC, "surpoid" = mean(proteine_animale))

biometry_PD <-  filter (biometry2,sequences == "normal"  )
biometry_PD <- filter (biometry_PD, proteine_animale != "NA")
biometry_PD <- summarise (biometry_PD, "normales" = mean(proteine_animale))

biometry_P <- bind_cols( biometry_PA, biometry_PD, biometry_PC, biometry_PB)

knitr::kable(biometry_P, digits = 2)
````

